// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpadpldjzexlqoeqtuzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYWRwbGRqemV4bHFvZXF0dXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMzQ2OTEsImV4cCI6MjA2MTYxMDY5MX0.trrhIfVa78e_jOo7u1xlQZ8L7oRf8cHu0-LbpgeAT7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);