// This file is automatically generated. Do not edit it directly.

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://gpadpldjzexlqoeqtuzq.supabase.co";
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseAnonKey) {
  throw new Error('Missing VITE_SUPABASE_ANON_KEY environment variable');
}

// Create a Supabase client with the service role key
export const supabase = createClient<Database>(
  supabaseUrl,
  supabaseAnonKey,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storageKey: 'tea-time-roster-auth',
      storage: window.localStorage
    }
  }
);